In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_excel('/Users/kuzaowuwei/Desktop/2022美赛/赛中数据/3指标体系/data/resolution_2.xlsx')
portfolio = df[['C','G','B']]



In [4]:
portfolio.shape

(1826, 3)

In [72]:
import tensorflow as tf
import numpy as np
from sklearn.datasets import load_iris
data=load_iris()
iris_target=data.target
iris_data=np.float32(data.data)

# iris_target=np.float32(tf.keras.utils.to_categorical(iris_target,num_classes=3))
# iris_target = np.random.rand(150,3)
# iris_target[:,0] = 0

# data: 1816 * 9
# target: 1826 * 3 => 1816 * 3
df = pd.read_excel('/Users/kuzaowuwei/Desktop/2022美赛/赛中数据/3指标体系/data/resolution_2.xlsx')
portfolio = df[['C','G','B']].values[10:]
df_i_g = pd.read_excel('/Users/kuzaowuwei/Desktop/2022美赛/赛中数据/3指标体系/data/gold_indicator.xlsx')
df_i_b = pd.read_excel('/Users/kuzaowuwei/Desktop/2022美赛/赛中数据/3指标体系/data/bitcoin_indicator.xlsx')
i_g = df_i_g.values
i_b = df_i_b.values
indicator = np.concatenate((i_g, i_b), axis = 1)
iris_target = portfolio.copy()
iris_data = indicator.copy()

batch_size = 100
iris_data=tf.data.Dataset.from_tensor_slices(iris_data).batch(batch_size)
iris_target=tf.data.Dataset.from_tensor_slices(iris_target).batch(batch_size)



model=tf.keras.models.Sequential()
# model.add(tf.keras.layers.Dense(64,activation='relu'))
# model.add(tf.keras.layers.Dense(128,activation='relu'))
model.add(tf.keras.layers.Dense(32,activation='relu'))
model.add(tf.keras.layers.Dense(3,activation='softmax'))
opt=tf.optimizers.Adam(1e-3)
for epoch in range(10):
    for _data,lable in zip(iris_data,iris_target):
        # if epoch == 0:
        #     print('_data',_data)
        with tf.GradientTape() as tape:
            logits=model(_data)
            # print(lable.shape, lable)
            # loss value needs to be modified

            def convert2prob(x, axis=1):
                row_sum = x.sum(axis=axis)
                row_sum = row_sum.reshape(-1,1)
                s = x/row_sum
                return s


            x = np.array(lable)
            true_prob = tf.convert_to_tensor(convert2prob(x))
            # print('lable',lable)
            loss_value = tf.reduce_mean(tf.keras.losses.mse(true_prob,logits))
            # print('true prob',true_prob)
            # print('pred prob',logits)

            # print(loss_value)
            # loss_value=tf.reduce_mean(tf.keras.losses.categorical_crossentropy(
            #         y_true=lable,y_pred=logits))
            # print('loss value:',loss_value)
            grads=tape.gradient(loss_value,model.trainable_variables)
            opt.apply_gradients(zip(grads,model.trainable_variables))
    print('Training loss is:',loss_value.numpy())


Training loss is: 0.24089983
Training loss is: 0.24089983
Training loss is: 0.24089983
Training loss is: 0.24089983
Training loss is: 0.24089983
Training loss is: 0.24089983
Training loss is: 0.24089983
Training loss is: 0.24089983
Training loss is: 0.24089983
Training loss is: 0.24089983


In [33]:
model.predict([[5.1 ,3.5 ,1.4, 0.2]])

array([[0.23195472, 0.38641495, 0.38163036]], dtype=float32)

In [47]:
temp1 = [[1,2,3.],[1,2,3.]]
temp2 =[ [3,8,7.], [3,8,5.]]

tf.keras.losses.mse(temp1, temp2)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([18.666666, 14.666667], dtype=float32)>

In [35]:
df = pd.read_excel('/Users/kuzaowuwei/Desktop/2022美赛/赛中数据/3指标体系/data/resolution_2.xlsx')
portfolio = df[['C','G','B']].values[10:]
df_i_g = pd.read_excel('/Users/kuzaowuwei/Desktop/2022美赛/赛中数据/3指标体系/data/gold_indicator.xlsx')
df_i_b = pd.read_excel('/Users/kuzaowuwei/Desktop/2022美赛/赛中数据/3指标体系/data/bitcoin_indicator.xlsx')
i_g = df_i_g.values
i_b = df_i_b.values
indicator = np.concatenate((i_g, i_b), axis = 1)
iris_target = portfolio.copy()
iris_data = indicator.copy()




(1816, 3)

In [70]:
def convert2prob(x, axis=1):
    row_sum = x.sum(axis=axis)
    row_sum = row_sum.reshape(-1,1)
    s = x/row_sum
    return s
t =np.array( [[1,2,3.],[3,2,1.]])
s = convert2prob(t)
print(s)

[[0.16666667 0.33333333 0.5       ]
 [0.5        0.33333333 0.16666667]]


In [74]:
model.predict([[1.20055005e+03, 1.21605005e+03, 1.19034998e+03, 3.96888878e+01,
       4.43275220e+02, 5.57572835e+01, 1.19822774e+03, 9.10516121e-01,
       2.76037629e-02, 9.18603638e+02, 9.06599976e+02, 8.17909973e+02,
       1.13534403e+02, 3.33851990e+02, 5.41290634e+01, 8.88525169e+02,
       3.15952668e+00, 2.76037629e-02]])

array([[0., 0., 1.]], dtype=float32)

In [73]:
indicator[123]

array([1.20055005e+03, 1.21605005e+03, 1.19034998e+03, 3.96888878e+01,
       4.43275220e+02, 5.57572835e+01, 1.19822774e+03, 9.10516121e-01,
       2.76037629e-02, 9.18603638e+02, 9.06599976e+02, 8.17909973e+02,
       1.13534403e+02, 3.33851990e+02, 5.41290634e+01, 8.88525169e+02,
       3.15952668e+00, 2.76037629e-02])